main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('accounts/signup/', views.signup, name='signup'),
  path('about/', views.about, name='about'),
  path('interests/', views.interests, name='interests'),
  path('detail/', views.profile_detail, name='detail'),
  path('matches/', views.matches, name='matches'),
  path('profiles/create_profile', views.ProfileCreate.as_view(), name='ProfileCreate'),
  path('profile/<int:pk>/update/', views.ProfileUpdate.as_view(), name='profile_update'),
  path('profile/<int:profile_id>/add_photo/', views.add_photo, name='add_photo'),
  path('interests/<int:profile_id>/assoc_interest/<int:interest_id>/', views.assoc_interest, name='assoc_interest'),
  path('interests/<int:profile_id>/remove_interest/<int:interest_id>/', views.remove_interest, name='remove_interest'),
  # path('interests/', views.InterestList.as_view(), name='interests_index'),
  path('interests/<int:pk>/', views.InterestDetail.as_view(), name='interest_detail'),
  path('interests/create/', views.InterestCreate.as_view(), name='interest_create'),
  path('interests/<int:pk>/update/', views.InterestUpdate.as_view(), name='interest_update'),
  path('interests/<int:pk>/delete/', views.InterestDelete.as_view(), name='interest_delete'),
]

sw_inder/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
import random 
from django.urls import reverse 
from django.contrib.auth.models import User

# Create your models here.


def get_match():
  match = random.random(82)
  print(match)

class Interest(models.Model):
  interest = models.TextField(max_length=200)

  def __str__(self):
    return self.interest

  def get_absolute_url(self):
    return reverse('detail')

 
class Profile(models.Model):
  name = models.CharField(max_length=50)
  species = models.CharField(max_length=50)
  hair_color = models.CharField(max_length=50)
  height = models.CharField(max_length=50)
  homeworld = models.CharField(max_length=50)
  about = models.CharField(max_length=50)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  interests = models.ManyToManyField(Interest)

  def get_absolute_url(self):
    return reverse('detail')
  
  def __str__(self):
    return f"Profile Id: {self.id}, User: {self.user}"

class Photo(models.Model):
    url = models.CharField(max_length=200)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for User: {self.profile_id} @{self.url}"

main_app/views.py
import os
import uuid
import boto3
import requests
import random
from pprint import pprint
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Profile, Photo, Interest

baseUrl = 'https://swapi.dev/api/'
r = requests.get(baseUrl + 'people/1')
r2 = requests.get('http://swapi.dev/api/planets/1')
people = r.json()



img = [
  'https://imgur.com/b4GrpJb.png', # luke and numb 1
  'https://imgur.com/IFG02gN.png', # c-3po 2
  'https://imgur.com/5ebf0mo.png', # r2-d2 3
  'https://imgur.com/1HICt2k.jpeg',# darth vader and num 4
  'https://imgur.com/HQjQeIx.png', # leia 5
  'https://imgur.com/kh6Oqlo.png', # owen lars 6
  'https://imgur.com/HzTNVj1.png', # beru 7
  'https://imgur.com/EUAFFcA.png', # r5-d4 8
  'https://imgur.com/aoqXU2e.png', # biggs 9
  'https://imgur.com/zfYrKRx.png', # obi wan 10
  'https://imgur.com/57ngyTT.png', # anakin 11
  'https://imgur.com/oRj5kom.png', # wwillhuff 12
  'https://imgur.com/7GlhiV6.png', # chewy 13
  'https://imgur.com/ZeuboXl.png', # han solo 14
  'https://imgur.com/QMu4ni1.png', # greedo 15
  'https://imgur.com/VBxeNwT.png', # jabba 16
  'https://imgur.com/Z5s6APX.png', # gorilla with sunglasses 17
  'https://imgur.com/UQvY2ec.png', # wedge antilles 18
  'https://imgur.com/Lcwknoz.png', # jek tono porkins 19
  'https://imgur.com/lzHfii9.png', # yoda 20
  'https://imgur.com/4W39iIq.png', # palpy 21
  'https://imgur.com/h7PrcY2.png', # oba 22
  'https://imgur.com/84eB0oN.png', # ig-88 23
  'https://imgur.com/1bKIIv8.png', # bossk 24
  'https://imgur.com/OXaYGXX.png', # lando 25
  'https://imgur.com/WG4qXwI.png', # lobot 26
  'https://imgur.com/rsLgCOM.png', # ackbar 27
  'https://imgur.com/R3F3LnB.png', # mon mothma 28
  'https://imgur.com/RQ6yHFg.png', # arvel crynyd 29
  'https://imgur.com/jDhVXQy.png', # wicket 30
  'https://imgur.com/6qamhZu.png', # nien numb 31
  'https://imgur.com/j5JaqM1.png', # qui gon 32
  'https://imgur.com/JJF7FRf.png', # nute gunray 33
  'https://imgur.com/w732wXd.png', # finis valorum 34
  'https://imgur.com/lI7gdQg.png', # padme 35
  'https://imgur.com/8Q4W7jG.png', # jar jar 36
  'https://imgur.com/rmI8rgU.png', # roos tarpals 37
  'https://imgur.com/yXDhoUQ.png', # rugor nass 38
  'https://imgur.com/LpwGYws.png', # ric olie 39
  'https://imgur.com/EIMot31.png', # watto 40
  'https://imgur.com/tSoIPDF.png', # sebulba 41
  'https://imgur.com/hWfV41y.png', # quarsh panaka 42
  'https://imgur.com/kBNvrrK.png', # shmi 43
  'https://imgur.com/NF3CTDm.png', # darth maul 44
  'https://imgur.com/lmd9feE.png', # bib fortuna 45
  'https://imgur.com/IDSVFMZ.png', # ayla secura 46
  'https://imgur.com/nVw9ijO.png', # ratts tyerel 47
  'https://imgur.com/kfIP4li.png', # dud bolt 48
  'https://imgur.com/w6blxA0.png', # gasgano 49
  'https://imgur.com/KTBo3pf.png', # ben quadinaros 50
  'https://imgur.com/HPTJokQ.png', # mace windu 51
  'https://imgur.com/hVYXuwT.png', # ki-adi-mundi 52
  'https://imgur.com/Ncjhgsr.png', # kit fisto 53
  'https://imgur.com/3IEiIvZ.png', # eeth koth 54
  'https://imgur.com/KAFQrwW.png', # adi gallia 55
  'https://imgur.com/rL8RDlu.png', # saesee tiin 56
  'https://imgur.com/3ErWWx1.png', # yarael poof 57
  'https://imgur.com/C3Pfsph.png', # plo koon 58
  'https://imgur.com/jFAUk39.png', # mas amedda 59
  'https://imgur.com/ZAWmhFh.png', # gregar typho 60
  'https://imgur.com/zQjnBsM.png', # corde 61
  'https://imgur.com/bmG842Q.png', # cliegg lars 62
  'https://imgur.com/AuUYvmi.png', # poggle the lesser 63
  'https://imgur.com/vjhvB2l.png', # luminara unduli 64
  'https://imgur.com/nfQCwy9.png', # barriss offee 65
  'https://imgur.com/umvhDi7.png', # dorme 66
  'https://imgur.com/HdS9kmU.png', # dooku 67
  'https://imgur.com/ZAAC2bL.png', # bail prestor organa 68
  'https://imgur.com/QrPPpg0.png', # jango fett 69
  'https://imgur.com/GoqMxOg.png', # zam wesell 70
  'https://imgur.com/Ev9EqQL.png', # dexter jettster 71
  'https://imgur.com/pymd4Mq.png', # lamu su 72
  'https://imgur.com/la2QKd0.png', # taun we 73
  'https://imgur.com/ogOfqx1.png', # taun we 74
  'https://imgur.com/P6i7utV.png', # r4-p17 75
  'https://imgur.com/9Fzcerb.png', # wat tambor 76
  'https://imgur.com/8qeRmgW.png', # san hill 77
  'https://imgur.com/HkoYTkJ.png', # shaak ti 78
  'https://imgur.com/kVxg1Jv.png', # grievous 79
  'https://imgur.com/3TA8x68.png', # tarfful 80
  'https://imgur.com/EYY4VgO.png', # raymus antilles 81
  'https://imgur.com/iGmB3mY.png', # sly moore 82
  'https://imgur.com/COrKVcP.png', # tion medon 83
]


# Create your views here.
def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('/profiles/create_profile')
    else:
      error_message = 'Invalid signup - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)  

class ProfileCreate(LoginRequiredMixin, CreateView) :
  model = Profile
  fields = ['name', 'species', 'hair_color', 'height', 'homeworld', 'about']

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class ProfileUpdate(UpdateView):
  model = Profile
  fields = ['name', 'species', 'hair_color', 'height', 'homeworld', 'about']

@login_required
def profile_detail(request):
  profile = Profile.objects.get(user=request.user)
  id_list = profile.interests.all().values_list('id')
  interests_profile_doesnt = Interest.objects.exclude(id__in=id_list)
  return render(request, 'main_app/detail.html', { 
    'profile': profile,
    'interests': interests_profile_doesnt
  })

def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'main_app/about.html')

@login_required
def interests(request):
  return render(request, 'main_app/interests.html')

class InterestList(ListView):
  model = Interest

class InterestDetail(DetailView):
  model = Interest

class InterestCreate(CreateView):
  model = Interest
  fields = '__all__'

class InterestUpdate(UpdateView):
  model = Interest
  fields = ['__all__']

class InterestDelete(DeleteView):
  model = Interest
  success_url = 'main_app/detail.html'

def assoc_interest(request, profile_id, interest_id):
  Profile.objects.get(id=profile_id).interests.add(interest_id)
  return redirect('detail')

def remove_interest(request, profile_id, interest_id):
  Profile.objects.get(id=profile_id).interests.remove(interest_id)
  return redirect('detail')

@login_required
def matches(request):
  rand_num = random.randint(1, 82)
  baseUrl = 'https://swapi.dev/api/'
  r = requests.get(baseUrl + 'people/' + str(rand_num))
  people = r.json()
  name = people['name']
  species = people['species']
  img_gen = []
  try: 
    img_gen = img[rand_num - 1]
  except IndexError:
    pass
  if not species:
    species_name = 'Unidentified Life-Form'
  else:
    species_req = requests.get(species[0])
    species_data = species_req.json()
    species_name = species_data['name']
  hair_color = people['hair_color'].capitalize()
  gender = people['gender'].capitalize()
  homeworld = people['homeworld']
  homeworld_req = requests.get(homeworld)
  homeworld_data = homeworld_req.json()
  homeworld_name = homeworld_data['name']
  return render(request, 'main_app/matches.html', { 'name': name, 'hair_color': hair_color, 'gender': gender, 'homeworld_name': homeworld_name, 'species_name': species_name, 'img_gen': img_gen})

def add_photo(request, profile_id):
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    try:
      bucket = os.environ['S3_BUCKET']
      s3.upload_fileobj(photo_file, bucket, key)
      url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
      Photo.objects.create(url=url, profile_id=profile_id)
    except Exception as e:
      print('An error occured uploading file to S3')
      print(e)
  return redirect('detail')

main_app/templates/main_app/about.html
{% extends 'base.html' %}

{% block content %}

<h1>About SW-inder</h1>
<p> Its hard not feel lonely no matter what galaxy you're in. Modern problems require modern solutions. Nothing has been
  done like this. Thats what we chose to create here. What if we made an app where distance wasn't an issue. If matches
  could be made across the galaxy. Well, here you have it...SW-inder. No one in the universe should be lonely! </p>
<img
  src="https://www.google.com/url?sa=i&url=https%3A%2F%2Ftenor.com%2Fview%2Fyoda-luke-skywalker-star-wars-eyes-closed-gif-16207222&psig=AOvVaw35RmyvNl6O5kPSHyFi9SfC&ust=1669158219685000&source=images&cd=vfe&ved=0CA4QjRxqFwoTCKCN-IaxwPsCFQAAAAAdAAAAABAE.gif"
  alt="">
<img src="https://media.tenor.com/nm_FQBDAVZcAAAAd/yoda-luke-skywalker.gif" width='500px' alt="">
{% endblock %}

main_app/templates/main_app/detail.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ profile.name }}</h1>


<section id="index">
  <div class="row">
    <div class="col s6">
      <div class="card">
        <div class="card-image card">
          <img src="{{photo.url}}">
        </div>
        <div class="card-content">
          <p>Species: {{ profile.species }}</p>
          <p>Hair: {{ profile.hair_color }}</p>
          <p>Height: {{ profile.height }}</p>
          <p>Homeworld: {{ profile.homeworld }}</p>
          <p>About: {{ profile.about }}</p>
        </div>
        <a href="{% url 'profile_update' profile.id %}" class="btn #263238 blue-grey darken-4">Edit!</a>
      </div>
    </div>

  </div>
  <div class="row">
    <div class="col s6">
      <h3>Your Interests</h3>
      {% if profile.interests.count %}
      {% for interest in profile.interests.all %}
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            <p>{{ interest.interest }}</p>
          </span>
        </div>
        <form action="{% url 'remove_interest' profile.id interest.id %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn #263238 blue-grey darken-4">Remove</button>
        </form>
      </div>
      {% endfor %}
      {% else %}
      <h5>No Interests?</h5>
      {% endif %}
    </div>
    <div class="col s6">
      <h3>Are you interested in:</h3>
      {% if interests.count %}
      {% for interest in interests.all %}
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            {{ interest.interest }}
          </span>
        </div>
        <div class="card-action">
          <form action="{% url 'assoc_interest' profile.id interest.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn #263238 blue-grey darken-4">Add</button>
          </form>
        </div>
      </div>
      {% endfor %}
      {% else %}
      <h5>Pick an Interest!</h5>
      {% endif %}
    </div>
  </div>
  <div class="row">
    <div class="col s6">
      {% for photo in profile.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}">
      {% empty %}
      <div class="card-panel  center-align">No Photos Uploaded</div>
      {% endfor %}
      <form action="{% url 'add_photo' profile.id %}" enctype="multipart/form-data" method="POST"
        class="card-panel black-text">
        {% csrf_token %}
        <input type="file" name="photo-file">
        <br><br>
        <button type="submit" class="btn #263238 blue-grey darken-4">Upload Photo</button>
      </form>
    </div>
  </div>
</section>

{% endblock %}

main_app/templates/main_app/interest_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ interest }}</span>
      </div>
      <div class="card-action">
        <a href="{% url 'interest_update' interest.id %}">Edit</a>
        <a href="{% url 'interest_delete' interest.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/interest_form.html
{% extends 'base.html' %}

{% block content %}
<section class="align-center">
  {% if object %}
  <h1>Edit <span class="grey-text">{{object.interest}}</span></h1>
  {% else %}
  <h1>Add Interest</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->

  <form class="white"" action="" method=" post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn grey">
  </form>

  {% endblock %}

main_app/templates/main_app/interests.html
{% extends 'base.html' %}

{% block content %}

<ul>
  <input type="checkbox">Outdoors
  <input type="checkbox">Traveling
  <input type="checkbox">Museums
  <input type="checkbox">Staying Indoors
</ul>
{% for int in interest_list %}
<a href="{% url 'interest_detail' interest.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ interest }}</span>
    </div>
  </div>
</a>
{% endfor %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.interest}}</span></h1>
{% else %}
<h1>Add interest</h1>
{% endif %}
<form action="{% url 'interest_create' %}" method="POST">
  <!-- <input type="textarea" rows="4" cols="20"> -->
  {% csrf_token %}
  <table>
    <textarea name="" id="" cols="30" rows="10"></textarea>
  </table>
  <input type="submit" value="Submit">
</form>
{% endblock %}

main_app/templates/main_app/matches.html
{% extends 'base.html' %}

{% block content %}

<section class="container center-align">
  <h3>Find Your Match!</h3>

  <div class="row">
    <div class="col s12 m6 offset-m2 l6 offset-l3 rounded">
      <div class="card #ef9a9a red lighten-3">
        <div class="card-image orange accent-2">
          <img src="{{ img_gen}}" height="400px">
          <span class="card-title"></span>
          <a href="{% url 'matches' %}" class="btn-floating halfway-fab waves-effect waves-light red pulse">EW!</a>
          <!-- <a class="btn-floating btn-large waves-effect waves-light blue pulse"><i class="material-icons">favorite</i></a> -->
        </div>
        <div class="card-content">
          {{ name }} <br>
          Species: {{ species_name }} <br>
          Hair Color: {{ hair_color }} <br>
          Gender: {{ gender }} <br>
          Homeworld: {{ homeworld_name }}
        </div>
      </div>
    </div>
  </div>
</section>



{% endblock %}

main_app/templates/main_app/profile_form.html
{% extends 'base.html' %}
{% block content %}
{% if object %}
<h1>Edit <span>{{ object.nickname }}</span></h1>
{% else %}
<h1>Create New Profile</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="POST">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/profile_list.html
{% extends 'base.html' %}

{% block content %}

<h1>Endzone Profile</h1>

{% if user %}
{% for p in profile %}
<section id="index">
  <div class="card z-depth-5">
    <div class="card-image waves-effect waves-block waves-light">
    </div>
    <div class="card-reveal">
      <p>Type: {{ p.name}}</p>
      <p>Brand: {{ p.species}}</p>
      <p>Model: {{ p.hair_color }}</p>
      <p>Color: {{ p.height }}</p>
      <p>Manufactured Date: {{ p.about }}</p>
    </div>
  </div>
</section>
{% endfor %}
{% endif %}
{% endblock %}